// <auto-generated />
namespace Passport.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedStampExperienceRoadMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedStampExperienceRoadMap));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241105121_changedStampExperienceRoadMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
